config/routes.rb
Rails.application.routes.draw do
  resources :matches, only: [:create, :index, :new] do
    resource :win_rate, only: [:show]
    resource :turn_summary, only: [:show]
    resource :deck_list, only: [:show]
  end
  resources :strategies, only: [:create, :edit, :index, :new, :show] do
    resources :priorities, only: [:new, :create]
  end
  resources :priorities, only: [:update]
end

app/models/strategy.rb
class Strategy < ActiveRecord::Base
  before_create :default_priorities
  has_and_belongs_to_many :matches
  has_many :game_strategies
  has_many :games, through: :game_strategies
  has_many :priorities

  DEFAULT_PRIORITIES = %w[
    Province
    Gold
    Silver
  ].freeze

  def default_priorities
    if priorities.empty?
      self.priorities = DEFAULT_PRIORITIES.map.with_index do |priority, index|
        Priority.new(card_type: priority, strategy: self, sequence: index)
      end
    end
  end
end

app/controllers/strategies_controller.rb
class StrategiesController < ApplicationController
  def create
    @strategy = Strategy.new(strategy_params)
    if @strategy.save
      flash[:sucess] = I18n.t("forms.strategies.create.success")
      redirect_to edit_strategy_url @strategy
    else
      render :new
    end
  end

  def edit
    @strategy = Strategy.find(params[:id])
  end

  def index
    @strategies = Strategy.all
  end

  def new
    @strategy = Strategy.new
  end

  def show
    @strategy = Strategy.find(params[:id])
  end

  private

  def strategy_params
    params.require(:strategy).permit(:name)
  end
end

app/views/strategies/_strategy.html.erb
<div class="strategy">
  <%= link_to strategy.name, strategy_path(strategy) %>
</div>

app/views/strategies/edit.html.slim
.container
  h1= "Edit #{@strategy.name} Strategy"
  h3 Priorities:
  ul
    - @strategy.priorities.each do |priority|
      = render "priorities/priority_form", strategy: @strategy, priority: priority

app/views/strategies/index.html.erb
<div class="container">
  <%= render @strategies %>
</div>

app/views/strategies/new.html.slim
.container
  h1 New Strategy
  = simple_form_for @strategy do |form|
    = form.input :name
    = form.submit "Create"

app/views/strategies/show.html.slim
.container
  = react_component("PriorityList", {priorities: @strategy.priorities.to_ary})
  = link_to(I18n.t("priorities.buttons.new"),
            new_strategy_priority_path(@strategy))